// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: com/itcoursee/core/audience.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 观众
type Audience int32

const (
	// 未知，不要使用
	Audience_AUDIENCE_UNSPECIFIED Audience = 0
	// 零基础或者初学者
	Audience_AUDIENCE_BEGINNER Audience = 1
	// 初级
	Audience_AUDIENCE_ELEMENTARY Audience = 2
	// 中级
	Audience_AUDIENCE_INTERMEDIATE Audience = 3
	// 高级
	Audience_AUDIENCE_ADVANCED Audience = 4
	// 架构师
	Audience_AUDIENCE_ARCHITECT Audience = 5
	// 技术总监
	Audience_AUDIENCE_CTO Audience = 6
)

// Enum value maps for Audience.
var (
	Audience_name = map[int32]string{
		0: "AUDIENCE_UNSPECIFIED",
		1: "AUDIENCE_BEGINNER",
		2: "AUDIENCE_ELEMENTARY",
		3: "AUDIENCE_INTERMEDIATE",
		4: "AUDIENCE_ADVANCED",
		5: "AUDIENCE_ARCHITECT",
		6: "AUDIENCE_CTO",
	}
	Audience_value = map[string]int32{
		"AUDIENCE_UNSPECIFIED":  0,
		"AUDIENCE_BEGINNER":     1,
		"AUDIENCE_ELEMENTARY":   2,
		"AUDIENCE_INTERMEDIATE": 3,
		"AUDIENCE_ADVANCED":     4,
		"AUDIENCE_ARCHITECT":    5,
		"AUDIENCE_CTO":          6,
	}
)

func (x Audience) Enum() *Audience {
	p := new(Audience)
	*p = x
	return p
}

func (x Audience) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Audience) Descriptor() protoreflect.EnumDescriptor {
	return file_com_itcoursee_core_audience_proto_enumTypes[0].Descriptor()
}

func (Audience) Type() protoreflect.EnumType {
	return &file_com_itcoursee_core_audience_proto_enumTypes[0]
}

func (x Audience) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Audience.Descriptor instead.
func (Audience) EnumDescriptor() ([]byte, []int) {
	return file_com_itcoursee_core_audience_proto_rawDescGZIP(), []int{0}
}

var File_com_itcoursee_core_audience_proto protoreflect.FileDescriptor

var file_com_itcoursee_core_audience_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2a, 0xb0, 0x01, 0x0a, 0x08, 0x41, 0x75, 0x64, 0x69,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x55, 0x44, 0x49, 0x45, 0x4e, 0x43, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15,
	0x0a, 0x11, 0x41, 0x55, 0x44, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x42, 0x45, 0x47, 0x49, 0x4e,
	0x4e, 0x45, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x55, 0x44, 0x49, 0x45, 0x4e, 0x43,
	0x45, 0x5f, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x41, 0x52, 0x59, 0x10, 0x02, 0x12, 0x19,
	0x0a, 0x15, 0x41, 0x55, 0x44, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4d, 0x45, 0x44, 0x49, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x55, 0x44,
	0x49, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x41, 0x44, 0x56, 0x41, 0x4e, 0x43, 0x45, 0x44, 0x10, 0x04,
	0x12, 0x16, 0x0a, 0x12, 0x41, 0x55, 0x44, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x41, 0x52, 0x43,
	0x48, 0x49, 0x54, 0x45, 0x43, 0x54, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x55, 0x44, 0x49,
	0x45, 0x4e, 0x43, 0x45, 0x5f, 0x43, 0x54, 0x4f, 0x10, 0x06, 0x42, 0x36, 0x0a, 0x12, 0x63, 0x6f,
	0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x50, 0x01, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63, 0x6f,
	0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_itcoursee_core_audience_proto_rawDescOnce sync.Once
	file_com_itcoursee_core_audience_proto_rawDescData = file_com_itcoursee_core_audience_proto_rawDesc
)

func file_com_itcoursee_core_audience_proto_rawDescGZIP() []byte {
	file_com_itcoursee_core_audience_proto_rawDescOnce.Do(func() {
		file_com_itcoursee_core_audience_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_itcoursee_core_audience_proto_rawDescData)
	})
	return file_com_itcoursee_core_audience_proto_rawDescData
}

var file_com_itcoursee_core_audience_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_itcoursee_core_audience_proto_goTypes = []interface{}{
	(Audience)(0), // 0: com.itcoursee.core.Audience
}
var file_com_itcoursee_core_audience_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_itcoursee_core_audience_proto_init() }
func file_com_itcoursee_core_audience_proto_init() {
	if File_com_itcoursee_core_audience_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_itcoursee_core_audience_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_itcoursee_core_audience_proto_goTypes,
		DependencyIndexes: file_com_itcoursee_core_audience_proto_depIdxs,
		EnumInfos:         file_com_itcoursee_core_audience_proto_enumTypes,
	}.Build()
	File_com_itcoursee_core_audience_proto = out.File
	file_com_itcoursee_core_audience_proto_rawDesc = nil
	file_com_itcoursee_core_audience_proto_goTypes = nil
	file_com_itcoursee_core_audience_proto_depIdxs = nil
}
