// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: itcoursee/core/courseware.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Courseware_Status int32

const (
	// 已创建
	Courseware_CREATED Courseware_Status = 0
	// 上传中
	Courseware_UPLOADING Courseware_Status = 1
	// 已完成
	Courseware_COMPLETED Courseware_Status = 2
)

// Enum value maps for Courseware_Status.
var (
	Courseware_Status_name = map[int32]string{
		0: "CREATED",
		1: "UPLOADING",
		2: "COMPLETED",
	}
	Courseware_Status_value = map[string]int32{
		"CREATED":   0,
		"UPLOADING": 1,
		"COMPLETED": 2,
	}
)

func (x Courseware_Status) Enum() *Courseware_Status {
	p := new(Courseware_Status)
	*p = x
	return p
}

func (x Courseware_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Courseware_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_itcoursee_core_courseware_proto_enumTypes[0].Descriptor()
}

func (Courseware_Status) Type() protoreflect.EnumType {
	return &file_itcoursee_core_courseware_proto_enumTypes[0]
}

func (x Courseware_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Courseware_Status.Descriptor instead.
func (Courseware_Status) EnumDescriptor() ([]byte, []int) {
	return file_itcoursee_core_courseware_proto_rawDescGZIP(), []int{0, 0}
}

type Courseware_Type int32

const (
	// 课程
	Courseware_COURSE Courseware_Type = 0
	// 讲次
	Courseware_LECTURE Courseware_Type = 1
)

// Enum value maps for Courseware_Type.
var (
	Courseware_Type_name = map[int32]string{
		0: "COURSE",
		1: "LECTURE",
	}
	Courseware_Type_value = map[string]int32{
		"COURSE":  0,
		"LECTURE": 1,
	}
)

func (x Courseware_Type) Enum() *Courseware_Type {
	p := new(Courseware_Type)
	*p = x
	return p
}

func (x Courseware_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Courseware_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_itcoursee_core_courseware_proto_enumTypes[1].Descriptor()
}

func (Courseware_Type) Type() protoreflect.EnumType {
	return &file_itcoursee_core_courseware_proto_enumTypes[1]
}

func (x Courseware_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Courseware_Type.Descriptor instead.
func (Courseware_Type) EnumDescriptor() ([]byte, []int) {
	return file_itcoursee_core_courseware_proto_rawDescGZIP(), []int{0, 1}
}

type Courseware_Subtype int32

const (
	// 附件
	Courseware_ATTACHMENT Courseware_Subtype = 0
	// 封面
	Courseware_COVER Courseware_Subtype = 1
	// 试听
	Courseware_AUDITION Courseware_Subtype = 2
)

// Enum value maps for Courseware_Subtype.
var (
	Courseware_Subtype_name = map[int32]string{
		0: "ATTACHMENT",
		1: "COVER",
		2: "AUDITION",
	}
	Courseware_Subtype_value = map[string]int32{
		"ATTACHMENT": 0,
		"COVER":      1,
		"AUDITION":   2,
	}
)

func (x Courseware_Subtype) Enum() *Courseware_Subtype {
	p := new(Courseware_Subtype)
	*p = x
	return p
}

func (x Courseware_Subtype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Courseware_Subtype) Descriptor() protoreflect.EnumDescriptor {
	return file_itcoursee_core_courseware_proto_enumTypes[2].Descriptor()
}

func (Courseware_Subtype) Type() protoreflect.EnumType {
	return &file_itcoursee_core_courseware_proto_enumTypes[2]
}

func (x Courseware_Subtype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Courseware_Subtype.Descriptor instead.
func (Courseware_Subtype) EnumDescriptor() ([]byte, []int) {
	return file_itcoursee_core_courseware_proto_rawDescGZIP(), []int{0, 2}
}

// 课件状态
type Courseware struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Courseware) Reset() {
	*x = Courseware{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itcoursee_core_courseware_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Courseware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Courseware) ProtoMessage() {}

func (x *Courseware) ProtoReflect() protoreflect.Message {
	mi := &file_itcoursee_core_courseware_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Courseware.ProtoReflect.Descriptor instead.
func (*Courseware) Descriptor() ([]byte, []int) {
	return file_itcoursee_core_courseware_proto_rawDescGZIP(), []int{0}
}

var File_itcoursee_core_courseware_proto protoreflect.FileDescriptor

var file_itcoursee_core_courseware_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x22, 0x96, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x77, 0x61, 0x72, 0x65,
	0x22, 0x33, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x50, 0x4c, 0x4f, 0x41,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45,
	0x54, 0x45, 0x44, 0x10, 0x02, 0x22, 0x1f, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x43, 0x4f, 0x55, 0x52, 0x53, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x45, 0x43,
	0x54, 0x55, 0x52, 0x45, 0x10, 0x01, 0x22, 0x32, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x54, 0x54, 0x41, 0x43, 0x48, 0x4d, 0x45, 0x4e, 0x54, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x41, 0x55, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x42, 0x35, 0x0a, 0x12, 0x63, 0x6f,
	0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x50, 0x01, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x65, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63, 0x6f, 0x72,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_itcoursee_core_courseware_proto_rawDescOnce sync.Once
	file_itcoursee_core_courseware_proto_rawDescData = file_itcoursee_core_courseware_proto_rawDesc
)

func file_itcoursee_core_courseware_proto_rawDescGZIP() []byte {
	file_itcoursee_core_courseware_proto_rawDescOnce.Do(func() {
		file_itcoursee_core_courseware_proto_rawDescData = protoimpl.X.CompressGZIP(file_itcoursee_core_courseware_proto_rawDescData)
	})
	return file_itcoursee_core_courseware_proto_rawDescData
}

var file_itcoursee_core_courseware_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_itcoursee_core_courseware_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_itcoursee_core_courseware_proto_goTypes = []interface{}{
	(Courseware_Status)(0),  // 0: itcoursee.core.Courseware.Status
	(Courseware_Type)(0),    // 1: itcoursee.core.Courseware.Type
	(Courseware_Subtype)(0), // 2: itcoursee.core.Courseware.Subtype
	(*Courseware)(nil),      // 3: itcoursee.core.Courseware
}
var file_itcoursee_core_courseware_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_itcoursee_core_courseware_proto_init() }
func file_itcoursee_core_courseware_proto_init() {
	if File_itcoursee_core_courseware_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_itcoursee_core_courseware_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Courseware); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itcoursee_core_courseware_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itcoursee_core_courseware_proto_goTypes,
		DependencyIndexes: file_itcoursee_core_courseware_proto_depIdxs,
		EnumInfos:         file_itcoursee_core_courseware_proto_enumTypes,
		MessageInfos:      file_itcoursee_core_courseware_proto_msgTypes,
	}.Build()
	File_itcoursee_core_courseware_proto = out.File
	file_itcoursee_core_courseware_proto_rawDesc = nil
	file_itcoursee_core_courseware_proto_goTypes = nil
	file_itcoursee_core_courseware_proto_depIdxs = nil
}
