// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: itcoursee/core/lecture_status.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lecture_Status int32

const (
	// 已创建
	Lecture_CREATED Lecture_Status = 0
	// 上传中
	Lecture_UPLOADING Lecture_Status = 10
	// 上传完成
	Lecture_UPLOADED Lecture_Status = 11
	// 转码中
	Lecture_CONVERTING Lecture_Status = 20
	// 转码完成
	Lecture_CONVERTED Lecture_Status = 21
)

// Enum value maps for Lecture_Status.
var (
	Lecture_Status_name = map[int32]string{
		0:  "CREATED",
		10: "UPLOADING",
		11: "UPLOADED",
		20: "CONVERTING",
		21: "CONVERTED",
	}
	Lecture_Status_value = map[string]int32{
		"CREATED":    0,
		"UPLOADING":  10,
		"UPLOADED":   11,
		"CONVERTING": 20,
		"CONVERTED":  21,
	}
)

func (x Lecture_Status) Enum() *Lecture_Status {
	p := new(Lecture_Status)
	*p = x
	return p
}

func (x Lecture_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lecture_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_itcoursee_core_lecture_status_proto_enumTypes[0].Descriptor()
}

func (Lecture_Status) Type() protoreflect.EnumType {
	return &file_itcoursee_core_lecture_status_proto_enumTypes[0]
}

func (x Lecture_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lecture_Status.Descriptor instead.
func (Lecture_Status) EnumDescriptor() ([]byte, []int) {
	return file_itcoursee_core_lecture_status_proto_rawDescGZIP(), []int{0, 0}
}

// 讲次状态
type Lecture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Lecture) Reset() {
	*x = Lecture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itcoursee_core_lecture_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lecture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lecture) ProtoMessage() {}

func (x *Lecture) ProtoReflect() protoreflect.Message {
	mi := &file_itcoursee_core_lecture_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lecture.ProtoReflect.Descriptor instead.
func (*Lecture) Descriptor() ([]byte, []int) {
	return file_itcoursee_core_lecture_status_proto_rawDescGZIP(), []int{0}
}

var File_itcoursee_core_lecture_status_proto protoreflect.FileDescriptor

var file_itcoursee_core_lecture_status_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x5c, 0x0a, 0x07, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x51, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x50, 0x4c, 0x4f, 0x41,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x0a, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44,
	0x45, 0x44, 0x10, 0x0b, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4e, 0x56, 0x45, 0x52, 0x54, 0x49,
	0x4e, 0x47, 0x10, 0x14, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x56, 0x45, 0x52, 0x54, 0x45,
	0x44, 0x10, 0x15, 0x42, 0x35, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x50, 0x01, 0x5a, 0x1d, 0x67, 0x69, 0x74,
	0x65, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_itcoursee_core_lecture_status_proto_rawDescOnce sync.Once
	file_itcoursee_core_lecture_status_proto_rawDescData = file_itcoursee_core_lecture_status_proto_rawDesc
)

func file_itcoursee_core_lecture_status_proto_rawDescGZIP() []byte {
	file_itcoursee_core_lecture_status_proto_rawDescOnce.Do(func() {
		file_itcoursee_core_lecture_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_itcoursee_core_lecture_status_proto_rawDescData)
	})
	return file_itcoursee_core_lecture_status_proto_rawDescData
}

var file_itcoursee_core_lecture_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_itcoursee_core_lecture_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_itcoursee_core_lecture_status_proto_goTypes = []interface{}{
	(Lecture_Status)(0), // 0: itcoursee.core.Lecture.Status
	(*Lecture)(nil),     // 1: itcoursee.core.Lecture
}
var file_itcoursee_core_lecture_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_itcoursee_core_lecture_status_proto_init() }
func file_itcoursee_core_lecture_status_proto_init() {
	if File_itcoursee_core_lecture_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_itcoursee_core_lecture_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lecture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itcoursee_core_lecture_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itcoursee_core_lecture_status_proto_goTypes,
		DependencyIndexes: file_itcoursee_core_lecture_status_proto_depIdxs,
		EnumInfos:         file_itcoursee_core_lecture_status_proto_enumTypes,
		MessageInfos:      file_itcoursee_core_lecture_status_proto_msgTypes,
	}.Build()
	File_itcoursee_core_lecture_status_proto = out.File
	file_itcoursee_core_lecture_status_proto_rawDesc = nil
	file_itcoursee_core_lecture_status_proto_goTypes = nil
	file_itcoursee_core_lecture_status_proto_depIdxs = nil
}
