// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: itcoursee/core/stage.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 阶段
type Stage int32

const (
	// 零基础、初学者
	Stage_BEGINNER Stage = 0
	// 初阶
	Stage_ELEMENTARY Stage = 1
	// 中阶
	Stage_INTERMEDIATE Stage = 2
	// 高阶
	Stage_ADVANCED Stage = 3
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "BEGINNER",
		1: "ELEMENTARY",
		2: "INTERMEDIATE",
		3: "ADVANCED",
	}
	Stage_value = map[string]int32{
		"BEGINNER":     0,
		"ELEMENTARY":   1,
		"INTERMEDIATE": 2,
		"ADVANCED":     3,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_itcoursee_core_stage_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_itcoursee_core_stage_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_itcoursee_core_stage_proto_rawDescGZIP(), []int{0}
}

var File_itcoursee_core_stage_proto protoreflect.FileDescriptor

var file_itcoursee_core_stage_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x69, 0x74,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2a, 0x45, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x4e, 0x45,
	0x52, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x41, 0x52,
	0x59, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4d, 0x45, 0x44, 0x49,
	0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x44, 0x56, 0x41, 0x4e, 0x43, 0x45,
	0x44, 0x10, 0x03, 0x42, 0x35, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x50, 0x01, 0x5a, 0x1d, 0x67, 0x69, 0x74,
	0x65, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_itcoursee_core_stage_proto_rawDescOnce sync.Once
	file_itcoursee_core_stage_proto_rawDescData = file_itcoursee_core_stage_proto_rawDesc
)

func file_itcoursee_core_stage_proto_rawDescGZIP() []byte {
	file_itcoursee_core_stage_proto_rawDescOnce.Do(func() {
		file_itcoursee_core_stage_proto_rawDescData = protoimpl.X.CompressGZIP(file_itcoursee_core_stage_proto_rawDescData)
	})
	return file_itcoursee_core_stage_proto_rawDescData
}

var file_itcoursee_core_stage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_itcoursee_core_stage_proto_goTypes = []interface{}{
	(Stage)(0), // 0: itcoursee.core.Stage
}
var file_itcoursee_core_stage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_itcoursee_core_stage_proto_init() }
func file_itcoursee_core_stage_proto_init() {
	if File_itcoursee_core_stage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itcoursee_core_stage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itcoursee_core_stage_proto_goTypes,
		DependencyIndexes: file_itcoursee_core_stage_proto_depIdxs,
		EnumInfos:         file_itcoursee_core_stage_proto_enumTypes,
	}.Build()
	File_itcoursee_core_stage_proto = out.File
	file_itcoursee_core_stage_proto_rawDesc = nil
	file_itcoursee_core_stage_proto_goTypes = nil
	file_itcoursee_core_stage_proto_depIdxs = nil
}
