// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: itcoursee/core/type.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上传类型
type Type int32

const (
	// 录播课
	Type_RECORD Type = 0
	// 公开课
	Type_PUBLIC Type = 1
	// 互动课
	Type_INTERACTIVE Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "RECORD",
		1: "PUBLIC",
		2: "INTERACTIVE",
	}
	Type_value = map[string]int32{
		"RECORD":      0,
		"PUBLIC":      1,
		"INTERACTIVE": 2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_itcoursee_core_type_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_itcoursee_core_type_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_itcoursee_core_type_proto_rawDescGZIP(), []int{0}
}

var File_itcoursee_core_type_proto protoreflect.FileDescriptor

var file_itcoursee_core_type_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x69, 0x74, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2a, 0x2f, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x49,
	0x4e, 0x54, 0x45, 0x52, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x42, 0x35, 0x0a, 0x12,
	0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x50, 0x01, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x65, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63,
	0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_itcoursee_core_type_proto_rawDescOnce sync.Once
	file_itcoursee_core_type_proto_rawDescData = file_itcoursee_core_type_proto_rawDesc
)

func file_itcoursee_core_type_proto_rawDescGZIP() []byte {
	file_itcoursee_core_type_proto_rawDescOnce.Do(func() {
		file_itcoursee_core_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_itcoursee_core_type_proto_rawDescData)
	})
	return file_itcoursee_core_type_proto_rawDescData
}

var file_itcoursee_core_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_itcoursee_core_type_proto_goTypes = []interface{}{
	(Type)(0), // 0: itcoursee.core.Type
}
var file_itcoursee_core_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_itcoursee_core_type_proto_init() }
func file_itcoursee_core_type_proto_init() {
	if File_itcoursee_core_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itcoursee_core_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itcoursee_core_type_proto_goTypes,
		DependencyIndexes: file_itcoursee_core_type_proto_depIdxs,
		EnumInfos:         file_itcoursee_core_type_proto_enumTypes,
	}.Build()
	File_itcoursee_core_type_proto = out.File
	file_itcoursee_core_type_proto_rawDesc = nil
	file_itcoursee_core_type_proto_goTypes = nil
	file_itcoursee_core_type_proto_depIdxs = nil
}
