// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: itcoursee/core/upload_type.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上传类型
type UploadType int32

const (
	// 未知，不要使用
	UploadType_UPLOAD_TYPE_UNSPECIFIED UploadType = 0
	// 课件
	UploadType_COURSEWARE UploadType = 1
	// 课程封面
	UploadType_COURSE_COVER UploadType = 2
	// 讲次视频
	UploadType_LECTURE_VIDEO UploadType = 3
)

// Enum value maps for UploadType.
var (
	UploadType_name = map[int32]string{
		0: "UPLOAD_TYPE_UNSPECIFIED",
		1: "COURSEWARE",
		2: "COURSE_COVER",
		3: "LECTURE_VIDEO",
	}
	UploadType_value = map[string]int32{
		"UPLOAD_TYPE_UNSPECIFIED": 0,
		"COURSEWARE":              1,
		"COURSE_COVER":            2,
		"LECTURE_VIDEO":           3,
	}
)

func (x UploadType) Enum() *UploadType {
	p := new(UploadType)
	*p = x
	return p
}

func (x UploadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadType) Descriptor() protoreflect.EnumDescriptor {
	return file_itcoursee_core_upload_type_proto_enumTypes[0].Descriptor()
}

func (UploadType) Type() protoreflect.EnumType {
	return &file_itcoursee_core_upload_type_proto_enumTypes[0]
}

func (x UploadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadType.Descriptor instead.
func (UploadType) EnumDescriptor() ([]byte, []int) {
	return file_itcoursee_core_upload_type_proto_rawDescGZIP(), []int{0}
}

var File_itcoursee_core_upload_type_proto protoreflect.FileDescriptor

var file_itcoursee_core_upload_type_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2a, 0x5e, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x17, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a,
	0x0a, 0x43, 0x4f, 0x55, 0x52, 0x53, 0x45, 0x57, 0x41, 0x52, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x43, 0x4f, 0x55, 0x52, 0x53, 0x45, 0x5f, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x02, 0x12,
	0x11, 0x0a, 0x0d, 0x4c, 0x45, 0x43, 0x54, 0x55, 0x52, 0x45, 0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f,
	0x10, 0x03, 0x42, 0x36, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x50, 0x01, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_itcoursee_core_upload_type_proto_rawDescOnce sync.Once
	file_itcoursee_core_upload_type_proto_rawDescData = file_itcoursee_core_upload_type_proto_rawDesc
)

func file_itcoursee_core_upload_type_proto_rawDescGZIP() []byte {
	file_itcoursee_core_upload_type_proto_rawDescOnce.Do(func() {
		file_itcoursee_core_upload_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_itcoursee_core_upload_type_proto_rawDescData)
	})
	return file_itcoursee_core_upload_type_proto_rawDescData
}

var file_itcoursee_core_upload_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_itcoursee_core_upload_type_proto_goTypes = []interface{}{
	(UploadType)(0), // 0: itcoursee.core.UploadType
}
var file_itcoursee_core_upload_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_itcoursee_core_upload_type_proto_init() }
func file_itcoursee_core_upload_type_proto_init() {
	if File_itcoursee_core_upload_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itcoursee_core_upload_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itcoursee_core_upload_type_proto_goTypes,
		DependencyIndexes: file_itcoursee_core_upload_type_proto_depIdxs,
		EnumInfos:         file_itcoursee_core_upload_type_proto_enumTypes,
	}.Build()
	File_itcoursee_core_upload_type_proto = out.File
	file_itcoursee_core_upload_type_proto_rawDesc = nil
	file_itcoursee_core_upload_type_proto_goTypes = nil
	file_itcoursee_core_upload_type_proto_depIdxs = nil
}
