// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.9
// source: com/itcoursee/core/courseware/type.proto

package courseware

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 类型
type Type int32

const (
	// 未知，不要使用
	Type_TYPE_UNSPECIFIED Type = 0
	// 课程
	Type_TYPE_COURSE Type = 1
	// 讲次
	Type_TYPE_LECTURE Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_COURSE",
		2: "TYPE_LECTURE",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_COURSE":      1,
		"TYPE_LECTURE":     2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_com_itcoursee_core_courseware_type_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_com_itcoursee_core_courseware_type_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_com_itcoursee_core_courseware_type_proto_rawDescGZIP(), []int{0}
}

var File_com_itcoursee_core_courseware_type_proto protoreflect.FileDescriptor

var file_com_itcoursee_core_courseware_type_proto_rawDesc = []byte{
	0x0a, 0x28, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x63, 0x6f, 0x6d, 0x2e,
	0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2a, 0x3f, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x43, 0x4f, 0x55, 0x52, 0x53, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x4c, 0x45, 0x43, 0x54, 0x55, 0x52, 0x45, 0x10, 0x02, 0x42, 0x52, 0x0a, 0x1d, 0x63, 0x6f,
	0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x77, 0x61, 0x72, 0x65, 0x50, 0x01, 0x5a, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x77,
	0x61, 0x72, 0x65, 0x3b, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x77, 0x61, 0x72, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_itcoursee_core_courseware_type_proto_rawDescOnce sync.Once
	file_com_itcoursee_core_courseware_type_proto_rawDescData = file_com_itcoursee_core_courseware_type_proto_rawDesc
)

func file_com_itcoursee_core_courseware_type_proto_rawDescGZIP() []byte {
	file_com_itcoursee_core_courseware_type_proto_rawDescOnce.Do(func() {
		file_com_itcoursee_core_courseware_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_itcoursee_core_courseware_type_proto_rawDescData)
	})
	return file_com_itcoursee_core_courseware_type_proto_rawDescData
}

var file_com_itcoursee_core_courseware_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_itcoursee_core_courseware_type_proto_goTypes = []interface{}{
	(Type)(0), // 0: com.itcoursee.core.courseware.Type
}
var file_com_itcoursee_core_courseware_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_itcoursee_core_courseware_type_proto_init() }
func file_com_itcoursee_core_courseware_type_proto_init() {
	if File_com_itcoursee_core_courseware_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_itcoursee_core_courseware_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_itcoursee_core_courseware_type_proto_goTypes,
		DependencyIndexes: file_com_itcoursee_core_courseware_type_proto_depIdxs,
		EnumInfos:         file_com_itcoursee_core_courseware_type_proto_enumTypes,
	}.Build()
	File_com_itcoursee_core_courseware_type_proto = out.File
	file_com_itcoursee_core_courseware_type_proto_rawDesc = nil
	file_com_itcoursee_core_courseware_type_proto_goTypes = nil
	file_com_itcoursee_core_courseware_type_proto_depIdxs = nil
}
