// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: com/itcoursee/core/kernel/price.proto

package kernel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 价格
type Price struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 播放
	Play int32 `protobuf:"varint,5,opt,name=play,proto3" json:"play,omitempty"`
	// 下载
	Download int32 `protobuf:"varint,6,opt,name=download,proto3" json:"download,omitempty"`
	// 市场
	Shop int32 `protobuf:"varint,7,opt,name=shop,proto3" json:"shop,omitempty"`
}

func (x *Price) Reset() {
	*x = Price{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_itcoursee_core_kernel_price_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_com_itcoursee_core_kernel_price_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_com_itcoursee_core_kernel_price_proto_rawDescGZIP(), []int{0}
}

func (x *Price) GetPlay() int32 {
	if x != nil {
		return x.Play
	}
	return 0
}

func (x *Price) GetDownload() int32 {
	if x != nil {
		return x.Download
	}
	return 0
}

func (x *Price) GetShop() int32 {
	if x != nil {
		return x.Shop
	}
	return 0
}

var File_com_itcoursee_core_kernel_price_proto protoreflect.FileDescriptor

var file_com_itcoursee_core_kernel_price_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x22, 0x4b, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6c, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x68, 0x6f, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x68, 0x6f, 0x70, 0x42,
	0x46, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x50, 0x01, 0x5a, 0x27,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c,
	0x3b, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_itcoursee_core_kernel_price_proto_rawDescOnce sync.Once
	file_com_itcoursee_core_kernel_price_proto_rawDescData = file_com_itcoursee_core_kernel_price_proto_rawDesc
)

func file_com_itcoursee_core_kernel_price_proto_rawDescGZIP() []byte {
	file_com_itcoursee_core_kernel_price_proto_rawDescOnce.Do(func() {
		file_com_itcoursee_core_kernel_price_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_itcoursee_core_kernel_price_proto_rawDescData)
	})
	return file_com_itcoursee_core_kernel_price_proto_rawDescData
}

var file_com_itcoursee_core_kernel_price_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_com_itcoursee_core_kernel_price_proto_goTypes = []interface{}{
	(*Price)(nil), // 0: com.itcoursee.core.kernel.Price
}
var file_com_itcoursee_core_kernel_price_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_itcoursee_core_kernel_price_proto_init() }
func file_com_itcoursee_core_kernel_price_proto_init() {
	if File_com_itcoursee_core_kernel_price_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_itcoursee_core_kernel_price_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Price); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_itcoursee_core_kernel_price_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_itcoursee_core_kernel_price_proto_goTypes,
		DependencyIndexes: file_com_itcoursee_core_kernel_price_proto_depIdxs,
		MessageInfos:      file_com_itcoursee_core_kernel_price_proto_msgTypes,
	}.Build()
	File_com_itcoursee_core_kernel_price_proto = out.File
	file_com_itcoursee_core_kernel_price_proto_rawDesc = nil
	file_com_itcoursee_core_kernel_price_proto_goTypes = nil
	file_com_itcoursee_core_kernel_price_proto_depIdxs = nil
}
