// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.9
// source: com/itcoursee/core/kernel/statement_subtype.proto

package kernel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 清单子类型
type StatementSubtype int32

const (
	// 未知，不要使用
	StatementSubtype_STATEMENT_SUBTYPE_UNSPECIFIED StatementSubtype = 0
	// 推荐
	StatementSubtype_STATEMENT_SUBTYPE_RECOMMEND StatementSubtype = 1
)

// Enum value maps for StatementSubtype.
var (
	StatementSubtype_name = map[int32]string{
		0: "STATEMENT_SUBTYPE_UNSPECIFIED",
		1: "STATEMENT_SUBTYPE_RECOMMEND",
	}
	StatementSubtype_value = map[string]int32{
		"STATEMENT_SUBTYPE_UNSPECIFIED": 0,
		"STATEMENT_SUBTYPE_RECOMMEND":   1,
	}
)

func (x StatementSubtype) Enum() *StatementSubtype {
	p := new(StatementSubtype)
	*p = x
	return p
}

func (x StatementSubtype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatementSubtype) Descriptor() protoreflect.EnumDescriptor {
	return file_com_itcoursee_core_kernel_statement_subtype_proto_enumTypes[0].Descriptor()
}

func (StatementSubtype) Type() protoreflect.EnumType {
	return &file_com_itcoursee_core_kernel_statement_subtype_proto_enumTypes[0]
}

func (x StatementSubtype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatementSubtype.Descriptor instead.
func (StatementSubtype) EnumDescriptor() ([]byte, []int) {
	return file_com_itcoursee_core_kernel_statement_subtype_proto_rawDescGZIP(), []int{0}
}

var File_com_itcoursee_core_kernel_statement_subtype_proto protoreflect.FileDescriptor

var file_com_itcoursee_core_kernel_statement_subtype_proto_rawDesc = []byte{
	0x0a, 0x31, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2a, 0x56,
	0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x21, 0x0a, 0x1d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x53, 0x55, 0x42, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x53, 0x54, 0x41, 0x54, 0x45, 0x4d, 0x45,
	0x4e, 0x54, 0x5f, 0x53, 0x55, 0x42, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x4d,
	0x4d, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x42, 0x46, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6b, 0x65, 0x72,
	0x6e, 0x65, 0x6c, 0x50, 0x01, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x3b, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_itcoursee_core_kernel_statement_subtype_proto_rawDescOnce sync.Once
	file_com_itcoursee_core_kernel_statement_subtype_proto_rawDescData = file_com_itcoursee_core_kernel_statement_subtype_proto_rawDesc
)

func file_com_itcoursee_core_kernel_statement_subtype_proto_rawDescGZIP() []byte {
	file_com_itcoursee_core_kernel_statement_subtype_proto_rawDescOnce.Do(func() {
		file_com_itcoursee_core_kernel_statement_subtype_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_itcoursee_core_kernel_statement_subtype_proto_rawDescData)
	})
	return file_com_itcoursee_core_kernel_statement_subtype_proto_rawDescData
}

var file_com_itcoursee_core_kernel_statement_subtype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_itcoursee_core_kernel_statement_subtype_proto_goTypes = []interface{}{
	(StatementSubtype)(0), // 0: com.itcoursee.core.kernel.StatementSubtype
}
var file_com_itcoursee_core_kernel_statement_subtype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_itcoursee_core_kernel_statement_subtype_proto_init() }
func file_com_itcoursee_core_kernel_statement_subtype_proto_init() {
	if File_com_itcoursee_core_kernel_statement_subtype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_itcoursee_core_kernel_statement_subtype_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_itcoursee_core_kernel_statement_subtype_proto_goTypes,
		DependencyIndexes: file_com_itcoursee_core_kernel_statement_subtype_proto_depIdxs,
		EnumInfos:         file_com_itcoursee_core_kernel_statement_subtype_proto_enumTypes,
	}.Build()
	File_com_itcoursee_core_kernel_statement_subtype_proto = out.File
	file_com_itcoursee_core_kernel_statement_subtype_proto_rawDesc = nil
	file_com_itcoursee_core_kernel_statement_subtype_proto_goTypes = nil
	file_com_itcoursee_core_kernel_statement_subtype_proto_depIdxs = nil
}
