// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.9
// source: com/itcoursee/core/review/approval.proto

package review

import (
	vo "github.com/itcoursee/core/vo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通过请求
type ApprovalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 审核标识
	// @gotags: validate:"required"
	Id int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty" validate:"required"`
}

func (x *ApprovalReq) Reset() {
	*x = ApprovalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_itcoursee_core_review_approval_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApprovalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalReq) ProtoMessage() {}

func (x *ApprovalReq) ProtoReflect() protoreflect.Message {
	mi := &file_com_itcoursee_core_review_approval_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalReq.ProtoReflect.Descriptor instead.
func (*ApprovalReq) Descriptor() ([]byte, []int) {
	return file_com_itcoursee_core_review_approval_proto_rawDescGZIP(), []int{0}
}

func (x *ApprovalReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 通过响应
type ApprovalRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 数据
	Review *vo.Review `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`
}

func (x *ApprovalRsp) Reset() {
	*x = ApprovalRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_itcoursee_core_review_approval_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApprovalRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRsp) ProtoMessage() {}

func (x *ApprovalRsp) ProtoReflect() protoreflect.Message {
	mi := &file_com_itcoursee_core_review_approval_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRsp.ProtoReflect.Descriptor instead.
func (*ApprovalRsp) Descriptor() ([]byte, []int) {
	return file_com_itcoursee_core_review_approval_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovalRsp) GetReview() *vo.Review {
	if x != nil {
		return x.Review
	}
	return nil
}

var File_com_itcoursee_core_review_approval_proto protoreflect.FileDescriptor

var file_com_itcoursee_core_review_approval_proto_rawDesc = []byte{
	0x0a, 0x28, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x2f, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x63, 0x6f, 0x6d, 0x2e,
	0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x1a, 0x22, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x6f, 0x2f, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x61, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x6f, 0x2e,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x06, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x42, 0x46,
	0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x50, 0x01, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x3b,
	0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_itcoursee_core_review_approval_proto_rawDescOnce sync.Once
	file_com_itcoursee_core_review_approval_proto_rawDescData = file_com_itcoursee_core_review_approval_proto_rawDesc
)

func file_com_itcoursee_core_review_approval_proto_rawDescGZIP() []byte {
	file_com_itcoursee_core_review_approval_proto_rawDescOnce.Do(func() {
		file_com_itcoursee_core_review_approval_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_itcoursee_core_review_approval_proto_rawDescData)
	})
	return file_com_itcoursee_core_review_approval_proto_rawDescData
}

var file_com_itcoursee_core_review_approval_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_itcoursee_core_review_approval_proto_goTypes = []interface{}{
	(*ApprovalReq)(nil), // 0: com.itcoursee.core.review.ApprovalReq
	(*ApprovalRsp)(nil), // 1: com.itcoursee.core.review.ApprovalRsp
	(*vo.Review)(nil),   // 2: com.itcoursee.core.vo.Review
}
var file_com_itcoursee_core_review_approval_proto_depIdxs = []int32{
	2, // 0: com.itcoursee.core.review.ApprovalRsp.review:type_name -> com.itcoursee.core.vo.Review
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_com_itcoursee_core_review_approval_proto_init() }
func file_com_itcoursee_core_review_approval_proto_init() {
	if File_com_itcoursee_core_review_approval_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_itcoursee_core_review_approval_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApprovalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_itcoursee_core_review_approval_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApprovalRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_itcoursee_core_review_approval_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_itcoursee_core_review_approval_proto_goTypes,
		DependencyIndexes: file_com_itcoursee_core_review_approval_proto_depIdxs,
		MessageInfos:      file_com_itcoursee_core_review_approval_proto_msgTypes,
	}.Build()
	File_com_itcoursee_core_review_approval_proto = out.File
	file_com_itcoursee_core_review_approval_proto_rawDesc = nil
	file_com_itcoursee_core_review_approval_proto_goTypes = nil
	file_com_itcoursee_core_review_approval_proto_depIdxs = nil
}
